# Generated by Django 3.0 on 2023-03-01 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



# Generated by Django 3.0 on 2023-02-25 12:44


def move_profiles(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('Profiles', 'Profile')

    print("essai")
    objs = list()

    fields = (
        'user',
        'favorite_city',
       
       
       
    )
    
    for old_object in OldProfile.objects.all():
        user = old_object.user
        favorite_city = old_object.favorite_city

        profil, created = NewProfile.objects.get_or_create(user=user , favorite_city=favorite_city)
        print(profil)
        objs.append(profil)
    
    NewProfile.objects.bulk_create(objs)
    



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_city', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            
        ),
        
    ]


