# Generated by Django 3.0 on 2023-02-25 12:44
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_profiles(apps, schema_editor):
    print(apps.get_models())
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('Profiles', 'Profile')


    objs = list()

    fields = (
        'user',
        'favorite_city',
       
       
       
    )
    print(OldProfile.objects.all())
    for old_object in OldProfile.objects.all():
        user = old_object.user
        favorite_city = old_object.favorite_city

        profil, created = NewProfile.objects.get_or_create(user=user , favorite_city=favorite_city)
        print(profil)
        objs.append(profil)
    

    

class Migration(migrations.Migration):


    dependencies = [
        ('Profiles', '0001_initial'),
        ('oc_lettings_site', '0003_auto_20230225_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
),
        migrations.RunPython(move_profiles, migrations.RunPython.noop),

    ]
    

