FROM python:3.8

EXPOSE 8000

RUN apt-get update -y \
    && apt-get install -y python3 python3-pip \
    && apt-get install -y unzip 




ADD oc_lettings_openclassroom.zip /home/root/

WORKDIR /home/root/

RUN unzip oc_lettings_openclassroom.zip

WORKDIR /home/root/oc_lettings_openclassroom

RUN pip install -r requirements.txt

RUN /usr/bin/python3 manage.py runserver 

#ENTRYPOINT [ "/usr/bin/python3", "manage.py", "runserver" ]