# fly.toml file generated for p3-official on 2023-03-30T18:07:43+02:00

app = "p3-official"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"
processes = []

[build]
  image = "flyio/hellofly:latest"

[env]
  MAX_PLAYER_COUNT = "15"
  MY_SPECIAL_ENV = "some_value"
  PORT = "8000"

[experimental]
  auto_rollback = true

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
