# Generated by Django 3.0 on 2023-02-25 12:44

from django.db import migrations, models

def move_lettings(apps, schema_editor):
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewLetting = apps.get_model('Lettings', 'Letting')
    NewAddress = apps.get_model('Lettings', 'Address')

    objs = list()

    fields = (
    'number',
    'street',
    'city',
    'state',
    'zip_code',
    'country_iso_code'
    )
    
    for old_object in OldLetting.objects.all():
        title = old_object.title
        old_address = old_object.address
        dict_fields = {k: getattr(old_address, k, None) for k in fields}
        address, created = NewAddress.objects.get_or_create(**dict_fields)
    
        new_letting = NewLetting(title=title, address=address)
        objs.append(new_letting)
    
        NewLetting.objects.bulk_create(objs)
    

class Migration(migrations.Migration):


    dependencies = [
        ('Lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='letting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),


    ]

